package com.rehab2.aac

object AacStarterContentV1 {
    fun items(): List<AacItem> = listOf(
        starter("no", "NE", "Ne.", "core.no", "CONFIRMATION", "core", listOf("ne", "zavrnitev"), fixedTopRowPosition = 1, imagePath = "system/no.png", iconSource = IconSource.SYSTEM),
        starter("yes", "DA", "Da.", "core.yes", "CONFIRMATION", "core", listOf("da", "potrditev"), fixedTopRowPosition = 2, imagePath = "system/yes.png", iconSource = IconSource.SYSTEM),
        starter("dont_understand", "NE RAZUMEM", "Ne razumem.", "core.dont_understand", "CONFIRMATION", "core", listOf("razumevanje", "ne_razumem"), fixedTopRowPosition = 3, imagePath = "system/dont_understand.png", iconSource = IconSource.SYSTEM),
        starter("thank_you", "HVALA", "Hvala.", "core.thank_you", "CONFIRMATION", "core", listOf("hvala", "zahvala"), fixedTopRowPosition = 4, imagePath = "system/thank_you.png", iconSource = IconSource.SYSTEM),
        starter("help", "POMOČ", "Prosim, pomagajte mi.", "core.help", "NEED", "core", listOf("pomoč", "nujno"), visibleUnderIds = listOf("need", "please", "care"), opensSubicons = true, children = listOf("help_drinking", "help_feeding", "wc", "dressing", "washing_help", "position"), questionByLanguage = mapOf("sl" to "Pri čem potrebuješ pomoč?"), imagePath = "system/help.png", iconSource = IconSource.SYSTEM),
        starter("wait", "POČAKAJ", "Počakajte, prosim.", "core.wait", "CORE_ACTION", "core", listOf("počakaj", "čas"), placements = pageOne(21), imagePath = "system/wait.png", iconSource = IconSource.SYSTEM),
        starter("repeat", "PONOVI", "Prosim, ponovite.", "core.repeat", "CORE_ACTION", "core", listOf("ponovi", "razumevanje"), placements = pageOne(20), opensSubicons = true, children = listOf("repeat_question", "repeat_last_sentence", "repeat_slower"), questionByLanguage = mapOf("sl" to "Kaj naj ponovim?"), imagePath = "system/repeat.png", iconSource = IconSource.SYSTEM),
        starter("slower", "POČASNEJE", "Prosim, govorite počasneje.", "core.slower", "CORE_ACTION", "core", listOf("počasneje", "razumevanje"), visibleUnderIds = listOf("please"), opensSubicons = true, children = listOf("slower_little", "slower_much"), questionByLanguage = mapOf("sl" to "Kako počasi?"), imagePath = "system/slower.png", iconSource = IconSource.SYSTEM),
        starter("understand", "RAZUMEM", "Razumem.", "core.understand", "CONFIRMATION", "core", listOf("razumem", "potrditev")),
        starter("people", "LJUDJE", "Ljudje.", "people.root", "PEOPLE", "people", listOf("ljudje", "osebe"), placements = pageOne(1), opensSubicons = true, children = listOf("miss_someone", "person_dusan", "person_zana", "person_sergej", "person_julija", "person_oksana", "person_inna", "person_franc", "person_other"), questionByLanguage = mapOf("sl" to "O kom želiš govoriti?"), imagePath = "system/people.png", iconSource = IconSource.SYSTEM),
        starter("need", "POTREBUJEM", "Potrebujem pomoč.", "need.root", "NEED", "need", listOf("potrebujem", "pomoč"), placements = pageOne(2), opensSubicons = true, children = listOf("help", "water", "food", "wc", "blanket", "wheelchair", "crutch", "doctor", "nurse", "therapy"), questionByLanguage = mapOf("sl" to "Kaj potrebuješ?"), imagePath = "system/need.png", iconSource = IconSource.SYSTEM),
        starter("problem", "TEŽAVA", "Imam težavo.", "problem.root", "NEED", "problem", listOf("težava", "problem"), placements = pageOne(3), opensSubicons = true, children = listOf("pain", "cannot", "cold", "hot", "afraid", "bad", "uncomfortable", "dont_know_problem"), questionByLanguage = mapOf("sl" to "Kaj je narobe?"), imagePath = "system/problem.png", iconSource = IconSource.SYSTEM),

        starter("family_group", "DRUŽINA", "Družina.", "people.family_group", "PEOPLE", "people", listOf("družina", "ljudje"), visibleUnderIds = listOf("legacy_people"), opensSubicons = true, children = listOf("person_dusan", "person_zana", "person_sergej", "person_julija", "person_oksana", "person_inna", "person_franc", "miss_you", "love_you", "contact_call"), questionByLanguage = mapOf("sl" to "Koga iz družine?", "uk" to "Кого з родини?", "en" to "Which family member?")),
        starter("friends_group", "PRIJATELJI", "Prijatelji.", "people.friends_group", "PEOPLE", "people", listOf("prijatelji", "ljudje"), visibleUnderIds = listOf("legacy_people"), opensSubicons = true, children = listOf("friend_1", "friend_2", "friend_3", "contact_message", "contact_call", "miss_you", "when_come", "come_to_me"), questionByLanguage = mapOf("sl" to "Kateri prijatelj?", "uk" to "Який друг?", "en" to "Which friend?")),
        starter("call", "POKLIČI", "Prosim, pokličite nekoga.", "people.call", "CORE_ACTION", "people", listOf("pokliči", "telefon"), visibleUnderIds = listOf("legacy_people"), opensSubicons = true, children = listOf("person_dusan", "person_zana", "person_sergej", "person_julija", "person_oksana", "person_inna", "person_franc", "doctor", "nurse"), questionByLanguage = mapOf("sl" to "Koga naj pokličem?", "uk" to "Кому подзвонити?", "en" to "Who should I call?")),
        starter("message", "SPOROČILO", "Pošljite sporočilo.", "people.message", "CORE_ACTION", "people", listOf("sporočilo"), visibleUnderIds = listOf("legacy_people")),
        starter("miss_someone", "POGREŠAM", "Pogrešam vas.", "people.miss_someone", "PEOPLE", "people", listOf("pogrešam", "ljudje"), visibleUnderIds = listOf("people", "person_dusan", "person_zana", "person_sergej", "person_julija", "person_oksana", "person_inna", "person_franc", "person_other"), opensSubicons = true, children = listOf("miss_little", "miss_very"), questionByLanguage = mapOf("sl" to "Kako zelo?"), imagePath = "system/miss_someone.png", iconSource = IconSource.SYSTEM),

        starter("thirsty", "ŽEJNA SEM", "Žejna sem.", "drink.thirsty", "DRINK", "drink", listOf("žejna", "piti"), placements = pageOne(4), opensSubicons = true, children = listOf("water", "tea", "coffee", "drink_fanta", "drink_coca_cola", "drink_pepsi", "juice", "drink_milk"), questionByLanguage = mapOf("sl" to "Kaj bi pila?", "uk" to "Що ти хочеш пити?", "en" to "What do you want to drink?"), imagePath = "system/thirsty.png", iconSource = IconSource.SYSTEM),
        starter("hungry", "LAČNA SEM", "Lačna sem.", "food.hungry", "FOOD", "food", listOf("lačna", "jesti"), placements = pageOne(5), opensSubicons = true, children = listOf("soup", "bread", "food_yogurt", "food_banana", "food_apple", "food_lunch", "food_dinner", "sweet"), questionByLanguage = mapOf("sl" to "Kaj bi jedla?", "uk" to "Що ти хочеш їсти?", "en" to "What do you want to eat?"), imagePath = "system/hungry.png", iconSource = IconSource.SYSTEM),
        starter("wc", "WC", "Moram na WC.", "care.wc", "NEED", "care", listOf("wc", "stranišče"), placements = pageOne(7), opensSubicons = true, children = listOf("wc_now", "wc_soon", "wc_help", "dressing_help", "washing_help"), questionByLanguage = mapOf("sl" to "Kaj potrebuješ glede WC?"), imagePath = "system/wc.png", iconSource = IconSource.SYSTEM),
        starter("tired", "UTRUJENA", "Utrujena sem.", "feeling.tired", "FEELING", "feeling", listOf("utrujena", "počutje"), placements = pageOne(8), visibleUnderIds = listOf("feeling"), imagePath = "system/tired.png", iconSource = IconSource.SYSTEM),

        starter("what_root", "KAJ?", "Kaj?", "question.what", "QUESTION", "question", listOf("kaj", "vprašanje"), placements = pageOne(11), opensSubicons = true, children = listOf("what_do", "what_is_this", "what_is_happening", "what_next", "what_did_i_say"), questionByLanguage = mapOf("sl" to "Kaj želiš vprašati?"), imagePath = "system/what.png", iconSource = IconSource.SYSTEM),
        starter("where_root", "KJE?", "Kje?", "question.where", "QUESTION", "question", listOf("kje", "vprašanje"), placements = pageOne(12), opensSubicons = true, children = listOf("where_zana", "where_dusan", "where_are_we", "where_phone", "where_wheelchair"), questionByLanguage = mapOf("sl" to "Kaj iščeš ali kje je?"), imagePath = "system/where.png", iconSource = IconSource.SYSTEM),
        starter("when_root", "KDAJ?", "Kdaj?", "question.when", "QUESTION", "question", listOf("kdaj", "vprašanje"), placements = pageOne(13), opensSubicons = true, children = listOf("when_come", "when_go", "when_therapy", "when_home", "when_eat"), questionByLanguage = mapOf("sl" to "Kaj želiš vprašati glede časa?"), imagePath = "system/when.png", iconSource = IconSource.SYSTEM),
        starter("home", "DOMOV", "Domov.", "place.home", "PLACE", "place", listOf("domov", "dom"), placements = pageOne(14), imagePath = "system/home.png", iconSource = IconSource.SYSTEM),
        starter("other", "DRUGO", "Drugo.", "core.other", "CORE_ACTION", "core", listOf("drugo"), placements = pageOne(15), imagePath = "system/other.png", iconSource = IconSource.SYSTEM),
        starter("real_world", "RESNIČNI SVET", "Resnični svet.", "scenario.real_world", "SCENARIO", "scenario", listOf("real_world", "scenarij"), placements = pageOne(16), opensSubicons = true, children = listOf("vending_drinks", "vending_coffee_tea", "shop", "restaurant", "transport"), questionByLanguage = mapOf("sl" to "Kje potrebuješ pomoč?"), imagePath = "system/real_world.png", iconSource = IconSource.SYSTEM),
        starter("what_do", "KAJ BOMO DELALI?", "Kaj bomo delali?", "activity.what_do", "QUESTION", "activity", listOf("kaj", "delali"), visibleUnderIds = listOf("what_root")),
        starter("what_is_this", "KAJ JE TO?", "Kaj je to?", "question.what_is_this", "QUESTION", "question", listOf("kaj", "to"), visibleUnderIds = listOf("what_root")),
        starter("what_is_happening", "KAJ SE DOGAJA?", "Kaj se dogaja?", "question.what_is_happening", "QUESTION", "question", listOf("kaj", "dogaja"), visibleUnderIds = listOf("what_root")),
        starter("what_next", "KAJ BO POTEM?", "Kaj bo potem?", "question.what_next", "QUESTION", "question", listOf("kaj", "potem"), visibleUnderIds = listOf("what_root")),
        starter("what_did_i_say", "KAJ SEM REKLA?", "Kaj sem rekla?", "question.what_did_i_say", "QUESTION", "question", listOf("kaj", "rekla"), visibleUnderIds = listOf("what_root")),
        starter("where_go", "KAM GREMO?", "Kam gremo?", "place.where_go", "QUESTION", "place", listOf("kam", "gremo"), visibleUnderIds = listOf("where_root")),
        starter("where_zana", "KJE JE ŽANA?", "Kje je Žana?", "question.where_zana", "QUESTION", "question", listOf("kje", "žana"), visibleUnderIds = listOf("where_root")),
        starter("where_dusan", "KJE JE DUŠAN?", "Kje je Dušan?", "question.where_dusan", "QUESTION", "question", listOf("kje", "dušan"), visibleUnderIds = listOf("where_root")),
        starter("where_are_we", "KJE SMO?", "Kje smo?", "question.where_are_we", "QUESTION", "question", listOf("kje", "smo"), visibleUnderIds = listOf("where_root")),
        starter("where_phone", "KJE JE TELEFON?", "Kje je telefon?", "question.where_phone", "QUESTION", "question", listOf("kje", "telefon"), visibleUnderIds = listOf("where_root")),
        starter("where_wheelchair", "KJE JE VOZIČEK?", "Kje je voziček?", "question.where_wheelchair", "QUESTION", "question", listOf("kje", "voziček"), visibleUnderIds = listOf("where_root")),
        starter("miss_little", "MALO", "Malo pogrešam.", "people.miss_little", "PEOPLE", "people", listOf("malo", "pogrešam"), visibleUnderIds = listOf("miss_someone")),
        starter("miss_very", "ZELO", "Zelo pogrešam.", "people.miss_very", "PEOPLE", "people", listOf("zelo", "pogrešam"), visibleUnderIds = listOf("miss_someone")),
        starter("repeat_question", "VPRAŠANJE", "Prosim, ponovi vprašanje.", "core.repeat_question", "CORE_ACTION", "core", listOf("ponovi", "vprašanje"), visibleUnderIds = listOf("repeat")),
        starter("repeat_last_sentence", "ZADNJI STAVEK", "Prosim, ponovi zadnji stavek.", "core.repeat_last_sentence", "CORE_ACTION", "core", listOf("ponovi", "zadnji", "stavek"), visibleUnderIds = listOf("repeat")),
        starter("repeat_slower", "POČASNEJE", "Prosim, ponovi počasneje.", "core.repeat_slower", "CORE_ACTION", "core", listOf("ponovi", "počasneje"), visibleUnderIds = listOf("repeat")),
        starter("slower_little", "MALO POČASNEJE", "Prosim, govori malo počasneje.", "core.slower_little", "CORE_ACTION", "core", listOf("malo", "počasneje"), visibleUnderIds = listOf("slower")),
        starter("slower_much", "ZELO POČASNEJE", "Prosim, govori zelo počasneje.", "core.slower_much", "CORE_ACTION", "core", listOf("zelo", "počasneje"), visibleUnderIds = listOf("slower")),
        starter("help_drinking", "PITJE", "Potrebujem pomoč pri pitju.", "care.help_drinking", "NEED", "care", listOf("pitje", "pomoč"), visibleUnderIds = listOf("help")),
        starter("help_feeding", "HRANJENJE", "Potrebujem pomoč pri hranjenju.", "care.help_feeding", "NEED", "care", listOf("hranjenje", "pomoč"), visibleUnderIds = listOf("help")),
        starter("dressing", "OBLAČENJE", "Potrebujem pomoč pri oblačenju.", "care.dressing.topic", "NEED", "care", listOf("oblačenje", "pomoč"), visibleUnderIds = listOf("help")),
        starter("position", "POLOŽAJ", "Potrebujem pomoč pri položaju.", "care.position.topic", "NEED", "care", listOf("položaj", "pomoč"), visibleUnderIds = listOf("help", "uncomfortable")),
        starter("i_want", "RADA BI", "Rada bi nekaj.", "core.i_want", "CORE_ACTION", "core", listOf("rada_bi", "želim"), visibleUnderIds = listOf("need")),
        starter("dont_want", "NOČEM", "Tega nočem.", "core.dont_want", "CORE_ACTION", "core", listOf("nočem", "zavrnitev"), visibleUnderIds = listOf("problem", "other")),
        starter("rest", "POČITEK", "Rada bi počivala.", "care.rest", "NEED", "care", listOf("počitek", "utrujena"), placements = pageOne(9), imagePath = "system/rest.png", iconSource = IconSource.SYSTEM),
        starter("drink", "PIJAČA", "Kaj bi pila?", "drink.root", "DRINK", "drink", listOf("pijača", "piti"), visibleUnderIds = listOf("legacy_drink"), opensSubicons = true, children = listOf("water", "tea", "coffee", "drink_fanta", "drink_coca_cola", "drink_pepsi", "juice", "drink_milk"), questionByLanguage = mapOf("sl" to "Kaj bi pila?", "uk" to "Що ти хочеш пити?", "en" to "What do you want to drink?")),
        starter("food", "HRANA", "Kaj bi jedla?", "food.root", "FOOD", "food", listOf("hrana", "jesti"), visibleUnderIds = listOf("need", "legacy_food"), opensSubicons = true, children = listOf("soup", "bread", "food_yogurt", "food_banana", "food_apple", "food_lunch", "food_dinner", "sweet"), questionByLanguage = mapOf("sl" to "Kaj bi jedla?", "uk" to "Що ти хочеш їсти?", "en" to "What do you want to eat?")),
        starter("feeling", "POČUTJE", "Kako se počutiš?", "feeling.root", "FEELING", "feeling", listOf("počutje"), placements = pageOne(17), opensSubicons = true, children = listOf("good", "bad", "tired", "afraid", "sad", "happy", "cold", "hot", "peace", "rest"), questionByLanguage = mapOf("sl" to "Kako se počutiš?", "uk" to "Як ти почуваєшся?", "en" to "How do you feel?")),
        starter("care", "NEGA", "Kaj potrebuješ?", "care.root", "NEED", "care", listOf("nega", "pomoč"), placements = pageOne(18), opensSubicons = true, children = listOf("wc", "washing_help", "dressing_help", "bed", "wheelchair", "crutch", "body_position", "movement_pain", "wait", "help"), questionByLanguage = mapOf("sl" to "Kaj potrebuješ?", "uk" to "Що тобі потрібно?", "en" to "What do you need?")),
        starter("health", "ZDRAVJE", "Kaj je z zdravjem?", "health.root", "NEED", "health", listOf("zdravje"), placements = pageOne(19), opensSubicons = true, children = listOf("pain", "head", "arm", "leg", "belly", "back", "throat", "medicine", "therapy", "doctor"), questionByLanguage = mapOf("sl" to "Kaj je z zdravjem?", "uk" to "Що зі здоров'ям?", "en" to "What is wrong with health?")),
        starter("more", "VEČ", "Kaj še potrebuješ?", "core.more", "CORE_ACTION", "core", listOf("več"), visibleUnderIds = listOf("legacy_more"), opensSubicons = true, children = listOf("repeat", "slower", "understand", "wheelchair", "not_safe", "stop_movement", "need_rest", "fear_falling", "move_me"), questionByLanguage = mapOf("sl" to "Kaj še potrebuješ?", "uk" to "Що ще потрібно?", "en" to "What else do you need?")),
        starter("pain_area", "BOLEČINA", "Kje te boli?", "pain.area", "PAIN", "pain", listOf("bolečina", "kje"), opensSubicons = true, children = listOf("head", "arm", "leg", "belly", "back", "chest", "throat"), questionByLanguage = mapOf("sl" to "Kje te boli?", "uk" to "Де тебе болить?", "en" to "Where does it hurt?")),

        starter("sister_zana", "SESTRA ŽANA", "Pokličite sestro Žano.", "people.sister_zana", "PEOPLE", "people", listOf("žana", "sestra"), placements = pageTwo(6)),
        starter("grandfather_sergej", "DEDEK SERGEJ", "Pokličite dedka Sergeja.", "people.grandfather_sergej", "PEOPLE", "people", listOf("sergej", "dedek"), placements = pageTwo(7)),
        starter("julija", "JULIJA", "Pokličite Julijo.", "people.julija", "PEOPLE", "people", listOf("julija", "prijatelji"), placements = pageTwo(8)),
        starter("oksana", "OKSANA", "Pokličite Oksano.", "people.oksana", "PEOPLE", "people", listOf("oksana", "prijatelji"), placements = pageTwo(9)),
        starter("inna", "INNA", "Pokličite Inno.", "people.inna", "PEOPLE", "people", listOf("inna", "prijatelji"), placements = pageTwo(10)),
        starter("franc", "FRANC", "Pokličite Franca.", "people.franc", "PEOPLE", "people", listOf("franc", "prijatelji"), placements = pageTwo(12)),
        starter("miss_you", "POGREŠAM TE", "Pogrešam te.", "people.miss_you", "PEOPLE", "people", listOf("pogrešam", "ljubezen"), placements = pageTwo(13)),
        starter("love_you", "RADA TE IMAM", "Rada te imam.", "people.love_you", "PEOPLE", "people", listOf("rada_te_imam", "ljubezen"), placements = pageTwo(14)),
        starter("sorry", "OPROSTI", "Oprosti.", "core.sorry", "FEELING", "core", listOf("oprosti"), placements = pageTwo(15), fixedTopRowPosition = 5, imagePath = "system/sorry.png", iconSource = IconSource.SYSTEM),
        starter("please", "PROSIM", "Prosim.", "core.please", "CORE_ACTION", "core", listOf("prosim"), placements = pageOne(10) + pageTwo(16), opensSubicons = true, children = listOf("help", "wait", "repeat", "slower", "come_to_me", "look_at_me", "turn_me", "fix_me"), questionByLanguage = mapOf("sl" to "Kaj želiš prositi?"), imagePath = "system/please.png", iconSource = IconSource.SYSTEM),
        starter("call_me", "POKLIČI ME", "Prosim, pokliči me.", "people.call_me", "CORE_ACTION", "people", listOf("pokliči_me"), placements = pageTwo(17)),
        starter("come_to_me", "PRIDI K MENI", "Prosim, pridi k meni.", "people.come_to_me", "CORE_ACTION", "people", listOf("pridi", "k_meni"), placements = pageOne(22) + pageTwo(19), imagePath = "system/come_to_me.png", iconSource = IconSource.SYSTEM),
        starter("look_at_me", "POGLEJ ME", "Prosim, poglej me.", "core.look_at_me", "CORE_ACTION", "core", listOf("poglej", "pozornost"), visibleUnderIds = listOf("please")),
        starter("turn_me", "OBRNI ME", "Prosim, obrni me.", "care.turn_me", "NEED", "care", listOf("obrni", "nega"), visibleUnderIds = listOf("please", "care"), opensSubicons = true, children = listOf("turn_left", "turn_right", "turn_back", "turn_side"), questionByLanguage = mapOf("sl" to "Kam?")),
        starter("fix_me", "POPRAVI ME", "Prosim, popravi me.", "care.fix_me", "NEED", "care", listOf("popravi", "nega"), visibleUnderIds = listOf("please", "care")),
        starter("turn_left", "LEVO", "Prosim, obrni me levo.", "care.turn_left", "NEED", "care", listOf("obrni", "levo"), visibleUnderIds = listOf("turn_me")),
        starter("turn_right", "DESNO", "Prosim, obrni me desno.", "care.turn_right", "NEED", "care", listOf("obrni", "desno"), visibleUnderIds = listOf("turn_me")),
        starter("turn_back", "NA HRBET", "Prosim, obrni me na hrbet.", "care.turn_back", "NEED", "care", listOf("obrni", "hrbet"), visibleUnderIds = listOf("turn_me")),
        starter("turn_side", "NA BOK", "Prosim, obrni me na bok.", "care.turn_side", "NEED", "care", listOf("obrni", "bok"), visibleUnderIds = listOf("turn_me")),
        starter("cannot", "NE MOREM", "Ne morem.", "core.cannot", "CORE_ACTION", "core", listOf("ne_morem", "zmorem"), placements = pageOne(23), opensSubicons = true, children = listOf("cannot_speak", "cannot_stand", "cannot_drink", "cannot_eat", "cannot_move", "cannot_understand"), questionByLanguage = mapOf("sl" to "Česa ne moreš?")),
        starter("cannot_speak", "GOVORITI", "Ne morem govoriti.", "problem.cannot_speak", "CORE_ACTION", "problem", listOf("ne_morem", "govoriti"), visibleUnderIds = listOf("cannot")),
        starter("cannot_stand", "VSTATI", "Ne morem vstati.", "problem.cannot_stand", "CORE_ACTION", "problem", listOf("ne_morem", "vstati"), visibleUnderIds = listOf("cannot")),
        starter("cannot_drink", "PITI", "Ne morem piti.", "problem.cannot_drink", "CORE_ACTION", "problem", listOf("ne_morem", "piti"), visibleUnderIds = listOf("cannot")),
        starter("cannot_eat", "JESTI", "Ne morem jesti.", "problem.cannot_eat", "CORE_ACTION", "problem", listOf("ne_morem", "jesti"), visibleUnderIds = listOf("cannot")),
        starter("cannot_move", "PREMAKNITI SE", "Ne morem se premakniti.", "problem.cannot_move", "CORE_ACTION", "problem", listOf("ne_morem", "premakniti"), visibleUnderIds = listOf("cannot")),
        starter("cannot_understand", "RAZUMETI", "Ne morem razumeti.", "problem.cannot_understand", "CORE_ACTION", "problem", listOf("ne_morem", "razumeti"), visibleUnderIds = listOf("cannot")),
        starter("cold_hot", "MRAZ/VROČE", "Mraz ali vroče.", "feeling.temperature", "FEELING", "feeling", listOf("mraz", "vroče", "temperatura"), placements = pageOne(24), opensSubicons = true, children = listOf("cold", "hot"), questionByLanguage = mapOf("sl" to "Kaj je?")),
        starter("contact_message", "SPOROČILO", "Želim poslati sporočilo.", "people.contact_message", "CORE_ACTION", "people", listOf("sporočilo", "ljudje"), placements = pageTwo(22)),
        starter("contact_call", "POKLIČI", "Prosim, pokličite to osebo.", "people.contact_call", "CORE_ACTION", "people", listOf("pokliči", "ljudje"), placements = pageTwo(23), visibleUnderIds = listOf("person_dusan", "person_zana", "person_sergej", "person_julija", "person_oksana", "person_inna", "person_franc", "person_other")),
        starter("contact_help", "POMOČ", "Prosim, pomagajte mi.", "people.contact_help", "NEED", "people", listOf("pomoč", "ljudje"), placements = pageTwo(24)),
        starter("back_to_main", "NAZAJ", "Nazaj.", "core.back", "CORE_ACTION", "core", listOf("nazaj"), placements = pageTwo(25) + pageFour(20), targetPageId = "page_1"),

        starter("person_dusan", "DUŠAN", "Dušan.", "person.dusan", "PEOPLE", "people", listOf("dušan", "družina"), visibleUnderIds = listOf("people", "family_group", "call"), opensSubicons = true, children = listOf("miss_someone", "contact_call", "person_where_is", "come_to_me", "love_you", "person_tell"), questionByLanguage = mapOf("sl" to "Kaj želiš povedati o Dušanu?"), imagePath = "contacts/dusan.jpg", iconSource = IconSource.PATIENT),
        starter("person_zana", "ŽANA", "Žana.", "person.zana", "PEOPLE", "people", listOf("žana", "družina"), visibleUnderIds = listOf("people", "family_group", "call"), opensSubicons = true, children = listOf("miss_someone", "contact_call", "person_where_is", "come_to_me", "love_you", "person_tell"), questionByLanguage = mapOf("sl" to "Kaj želiš povedati o Žani?"), imagePath = "contacts/zana.jpg", iconSource = IconSource.PATIENT),
        starter("person_sergej", "SERGEJ", "Sergej.", "person.sergej", "PEOPLE", "people", listOf("sergej", "družina"), visibleUnderIds = listOf("people", "family_group", "call"), opensSubicons = true, children = listOf("miss_someone", "contact_call", "person_where_is", "come_to_me", "love_you", "person_tell"), questionByLanguage = mapOf("sl" to "Kaj želiš povedati o Sergeju?"), imagePath = "contacts/sergej.jpg", iconSource = IconSource.PATIENT),
        starter("person_julija", "JULIJA", "Julija.", "person.julija", "PEOPLE", "people", listOf("julija", "družina"), visibleUnderIds = listOf("people", "family_group", "call"), opensSubicons = true, children = listOf("miss_someone", "contact_call", "person_where_is", "come_to_me", "love_you", "person_tell"), questionByLanguage = mapOf("sl" to "Kaj želiš povedati o Juliji?"), imagePath = "contacts/julija.jpg", iconSource = IconSource.PATIENT),
        starter("person_oksana", "OKSANA", "Oksana.", "person.oksana", "PEOPLE", "people", listOf("oksana", "družina"), visibleUnderIds = listOf("people", "family_group", "call"), opensSubicons = true, children = listOf("miss_someone", "contact_call", "person_where_is", "come_to_me", "love_you", "person_tell"), questionByLanguage = mapOf("sl" to "Kaj želiš povedati o Oksani?"), imagePath = "contacts/oksana.jpg", iconSource = IconSource.PATIENT),
        starter("person_inna", "INNA", "Inna.", "person.inna", "PEOPLE", "people", listOf("inna", "družina"), visibleUnderIds = listOf("people", "family_group", "call"), opensSubicons = true, children = listOf("miss_someone", "contact_call", "person_where_is", "come_to_me", "love_you", "person_tell"), questionByLanguage = mapOf("sl" to "Kaj želiš povedati o Inni?"), imagePath = "contacts/inna.jpg", iconSource = IconSource.PATIENT),
        starter("person_franc", "FRANC", "Franc.", "person.franc", "PEOPLE", "people", listOf("franc", "družina"), visibleUnderIds = listOf("people", "family_group", "call"), opensSubicons = true, children = listOf("miss_someone", "contact_call", "person_where_is", "come_to_me", "love_you", "person_tell"), questionByLanguage = mapOf("sl" to "Kaj želiš povedati o Francu?"), imagePath = "contacts/franc.jpg", iconSource = IconSource.PATIENT),
        starter("person_other", "DRUGO", "Druga oseba.", "person.other", "PEOPLE", "people", listOf("drugo", "oseba"), visibleUnderIds = listOf("people"), opensSubicons = true, children = listOf("miss_someone", "contact_call", "person_where_is", "come_to_me", "love_you", "person_tell"), questionByLanguage = mapOf("sl" to "Kaj želiš povedati o tej osebi?")),
        starter("person_where_is", "KJE JE", "Kje je?", "people.person_where_is", "QUESTION", "people", listOf("kje", "oseba"), visibleUnderIds = listOf("person_dusan", "person_zana", "person_sergej", "person_julija", "person_oksana", "person_inna", "person_franc", "person_other")),
        starter("person_tell", "POVEJ MU/JI", "Povej mu ali ji.", "people.person_tell", "CORE_ACTION", "people", listOf("povej", "oseba"), visibleUnderIds = listOf("person_dusan", "person_zana", "person_sergej", "person_julija", "person_oksana", "person_inna", "person_franc", "person_other")),
        starter("friend_1", "PRIJATELJ 1", "Prijatelj.", "person.friend_1", "PEOPLE", "people", listOf("prijatelj", "placeholder"), visibleUnderIds = listOf("friends_group"), imagePath = "patient/contacts/friend_1.jpg", iconSource = IconSource.PATIENT),
        starter("friend_2", "PRIJATELJ 2", "Prijatelj.", "person.friend_2", "PEOPLE", "people", listOf("prijatelj", "placeholder"), visibleUnderIds = listOf("friends_group"), imagePath = "patient/contacts/friend_2.jpg", iconSource = IconSource.PATIENT),
        starter("friend_3", "PRIJATELJ 3", "Prijatelj.", "person.friend_3", "PEOPLE", "people", listOf("prijatelj", "placeholder"), visibleUnderIds = listOf("friends_group"), imagePath = "patient/contacts/friend_3.jpg", iconSource = IconSource.PATIENT),

        starter("water", "VODA", "Rada bi vodo.", "drink.water", "DRINK", "drink", listOf("voda", "piti"), placements = pageThree(6), visibleUnderIds = listOf("drink", "thirsty", "need"), imagePath = "custom/drinks/water.jpg", iconSource = IconSource.CUSTOM),
        starter("water_detail", "VODA PODROBNO", "Kakšno vodo?", "drink.water.detail", "QUESTION", "drink", listOf("voda", "podrobno", "kakšna"), visibleUnderIds = listOf("drink", "thirsty")),
        starter("cold_water", "MRZLA", "Rada bi mrzlo vodo.", "drink.water.cold", "DRINK", "drink", listOf("mrzla", "voda"), visibleUnderIds = listOf("water_detail"), addsToSentence = true),
        starter("warm_water", "TOPLA", "Rada bi toplo vodo.", "drink.water.warm", "DRINK", "drink", listOf("topla", "voda"), visibleUnderIds = listOf("water_detail"), addsToSentence = true),
        starter("non_sparkling_water", "NEGAZIRANA", "Rada bi negazirano vodo.", "drink.water.non_sparkling", "DRINK", "drink", listOf("negazirana", "voda"), visibleUnderIds = listOf("water_detail"), addsToSentence = true),
        starter("sparkling_water", "GAZIRANA", "Rada bi gazirano vodo.", "drink.water.sparkling", "DRINK", "drink", listOf("gazirana", "voda"), visibleUnderIds = listOf("water_detail"), addsToSentence = true),
        starter("coffee", "KAVA", "Rada bi kavo.", "drink.coffee", "DRINK", "drink", listOf("kava", "piti"), placements = pageThree(7), visibleUnderIds = listOf("drink", "thirsty"), imagePath = "custom/drinks/coffee.jpg", iconSource = IconSource.CUSTOM),
        starter("tea", "ČAJ", "Rada bi čaj.", "drink.tea", "DRINK", "drink", listOf("čaj", "piti"), placements = pageThree(8), visibleUnderIds = listOf("drink", "thirsty"), imagePath = "custom/drinks/tea.jpg", iconSource = IconSource.CUSTOM),
        starter("juice", "SOK", "Rada bi sok.", "drink.juice", "DRINK", "drink", listOf("sok", "piti"), placements = pageThree(9), visibleUnderIds = listOf("drink", "thirsty"), imagePath = "custom/drinks/juice.jpg", iconSource = IconSource.CUSTOM),
        starter("drink_fanta", "FANTA", "Rada bi Fanto.", "drink.fanta", "DRINK", "drink", listOf("fanta", "piti"), visibleUnderIds = listOf("drink", "thirsty"), imagePath = "custom/drinks/drink_fanta.jpg", iconSource = IconSource.CUSTOM),
        starter("drink_coca_cola", "COCA COLA", "Rada bi Coca Colo.", "drink.coca_cola", "DRINK", "drink", listOf("coca_cola", "piti"), visibleUnderIds = listOf("drink", "thirsty"), imagePath = "custom/drinks/drink_coca_cola.jpg", iconSource = IconSource.CUSTOM),
        starter("drink_pepsi", "PEPSI", "Rada bi Pepsi.", "drink.pepsi", "DRINK", "drink", listOf("pepsi", "piti"), visibleUnderIds = listOf("drink", "thirsty"), imagePath = "custom/drinks/drink_pepsi.jpg", iconSource = IconSource.CUSTOM),
        starter("drink_milk", "MLEKO", "Rada bi mleko.", "drink.milk", "DRINK", "drink", listOf("mleko", "piti"), visibleUnderIds = listOf("drink", "thirsty"), imagePath = "custom/drinks/drink_milk.jpg", iconSource = IconSource.CUSTOM),
        starter("drink_warm", "TOPLO", "Rada bi toplo pijačo.", "drink.warm", "DRINK", "drink", listOf("toplo", "piti"), visibleUnderIds = listOf("drink", "thirsty")),
        starter("drink_cold", "HLADNO", "Rada bi hladno pijačo.", "drink.cold", "DRINK", "drink", listOf("hladno", "piti"), visibleUnderIds = listOf("drink", "thirsty")),
        starter("drink_small", "MALO", "Samo malo, prosim.", "drink.small", "DRINK", "drink", listOf("malo", "piti"), visibleUnderIds = listOf("drink", "thirsty")),
        starter("drink_more", "VEČ", "Še malo, prosim.", "drink.more", "DRINK", "drink", listOf("več", "piti"), visibleUnderIds = listOf("drink", "thirsty")),
        starter("drink_no_additive", "BREZ DODATKA", "Rada bi brez dodatka.", "drink.no_additive", "DRINK", "drink", listOf("brez", "dodatek", "piti"), visibleUnderIds = listOf("drink_fanta")),
        starter("coffee_plain", "NAVADNA", "Rada bi navadno kavo.", "drink.coffee.plain", "DRINK", "drink", listOf("navadna", "kava"), visibleUnderIds = listOf("coffee")),
        starter("coffee_white", "BELA", "Rada bi belo kavo.", "drink.coffee.white", "DRINK", "drink", listOf("bela", "kava"), visibleUnderIds = listOf("coffee")),
        starter("coffee_cappuccino", "CAPPUCCINO", "Rada bi cappuccino.", "drink.coffee.cappuccino", "DRINK", "drink", listOf("cappuccino", "kava"), visibleUnderIds = listOf("coffee")),
        starter("tea_large", "VELIK ČAJ", "Rada bi velik čaj.", "drink.tea.large", "DRINK", "drink", listOf("velik", "čaj"), visibleUnderIds = listOf("tea")),
        starter("tea_regular", "NAVADEN ČAJ", "Rada bi čaj.", "drink.tea.regular", "DRINK", "drink", listOf("navaden", "čaj"), visibleUnderIds = listOf("tea")),
        starter("not_thirsty", "NISEM ŽEJNA", "Nisem žejna.", "drink.not_thirsty", "DRINK", "drink", listOf("nisem_žejna", "piti"), visibleUnderIds = listOf("drink", "thirsty")),

        starter("not_hungry", "NISEM LAČNA", "Nisem lačna.", "food.not_hungry", "FOOD", "food", listOf("nisem_lačna", "jesti"), visibleUnderIds = listOf("food", "hungry")),
        starter("soup", "JUHA", "Rada bi jedla juho.", "food.soup", "FOOD", "food", listOf("juha", "jesti"), placements = pageThree(10), imagePath = "custom/food/soup.jpg", iconSource = IconSource.CUSTOM),
        starter("bread", "KRUH", "Rada bi jedla kruh.", "food.bread", "FOOD", "food", listOf("kruh", "jesti"), placements = pageThree(11), imagePath = "custom/food/bread.jpg", iconSource = IconSource.CUSTOM),
        starter("fruit", "SADJE", "Rada bi jedla sadje.", "food.fruit", "FOOD", "food", listOf("sadje", "jesti"), placements = pageThree(12)),
        starter("meat", "MESO", "Rada bi jedla meso.", "food.meat", "FOOD", "food", listOf("meso", "jesti"), placements = pageThree(13)),
        starter("sweet", "SLADKO", "Rada bi nekaj sladkega.", "food.sweet", "FOOD", "food", listOf("sladko", "jesti"), placements = pageThree(14), imagePath = "custom/food/sweet.jpg", iconSource = IconSource.CUSTOM),
        starter("other_food", "DRUGO", "Rada bi nekaj drugega.", "food.other", "FOOD", "food", listOf("drugo", "jesti"), placements = pageThree(15)),
        starter("food_yogurt", "JOGURT", "Rada bi jogurt.", "food.yogurt", "FOOD", "food", listOf("jogurt", "jesti"), visibleUnderIds = listOf("food", "hungry"), imagePath = "custom/food/yogurt.jpg", iconSource = IconSource.CUSTOM),
        starter("food_banana", "BANANA", "Rada bi banano.", "food.banana", "FOOD", "food", listOf("banana", "jesti"), visibleUnderIds = listOf("food", "hungry"), imagePath = "custom/food/banana.jpg", iconSource = IconSource.CUSTOM),
        starter("food_apple", "JABOLKO", "Rada bi jabolko.", "food.apple", "FOOD", "food", listOf("jabolko", "jesti"), visibleUnderIds = listOf("food", "hungry"), imagePath = "custom/food/apple.jpg", iconSource = IconSource.CUSTOM),
        starter("food_lunch", "KOSILO", "Rada bi kosilo.", "food.lunch", "FOOD", "food", listOf("kosilo", "jesti"), visibleUnderIds = listOf("food", "hungry"), imagePath = "custom/food/meal.jpg", iconSource = IconSource.CUSTOM),
        starter("food_dinner", "VEČERJA", "Rada bi večerjo.", "food.dinner", "FOOD", "food", listOf("večerja", "jesti"), visibleUnderIds = listOf("food", "hungry"), imagePath = "custom/food/dinner.jpg", iconSource = IconSource.CUSTOM),
        starter("food_little", "MALO", "Rada bi malo.", "food.little", "FOOD", "food", listOf("malo", "jesti"), visibleUnderIds = listOf("food", "hungry")),
        starter("food_more", "ŠE", "Še malo, prosim.", "food.more", "FOOD", "food", listOf("še", "jesti"), visibleUnderIds = listOf("food", "hungry")),
        starter("food_enough", "DOVOLJ", "Dovolj je.", "food.enough", "FOOD", "food", listOf("dovolj", "jesti"), visibleUnderIds = listOf("food", "hungry")),
        starter("food_later", "KASNEJE", "Kasneje bi jedla.", "food.later", "FOOD", "food", listOf("kasneje", "jesti"), visibleUnderIds = listOf("food", "hungry")),

        starter("diaper", "PLENICA", "Prosim, zamenjajte mi plenico.", "care.diaper", "NEED", "care", listOf("plenica", "nega"), visibleUnderIds = listOf("care")),
        starter("wc_now", "TAKOJ", "Moram takoj na WC.", "care.wc.now", "NEED", "care", listOf("takoj", "wc"), visibleUnderIds = listOf("wc")),
        starter("wc_soon", "KMALU", "Kmalu moram na WC.", "care.wc.soon", "NEED", "care", listOf("kmalu", "wc"), visibleUnderIds = listOf("wc")),
        starter("wc_help", "POMOČ", "Potrebujem pomoč za WC.", "care.wc.help", "NEED", "care", listOf("pomoč", "wc"), visibleUnderIds = listOf("wc")),
        starter("dressing_help", "PREOBLEČI", "Prosim, preoblecite me.", "care.dressing", "NEED", "care", listOf("preobleči", "nega"), visibleUnderIds = listOf("care")),
        starter("washing_help", "UMIVANJE", "Prosim, pomagajte mi pri umivanju.", "care.washing", "NEED", "care", listOf("umivanje", "nega"), visibleUnderIds = listOf("care")),
        starter("body_position", "POPRAVI ME", "Prosim, popravite moj položaj.", "care.position", "NEED", "care", listOf("položaj", "nega"), visibleUnderIds = listOf("care")),
        starter("pillow", "BLAZINA", "Prosim, popravite blazino.", "care.pillow", "NEED", "care", listOf("blazina", "udobje"), visibleUnderIds = listOf("care")),
        starter("blanket", "ODEJA", "Prosim, popravite odejo.", "care.blanket", "NEED", "care", listOf("odeja", "udobje"), visibleUnderIds = listOf("care", "need")),
        starter("uncomfortable", "NEUDOBNO", "Neudobno mi je.", "care.uncomfortable", "FEELING", "care", listOf("neudobno", "udobje"), placements = pageOne(25), visibleUnderIds = listOf("care", "problem"), opensSubicons = true, children = listOf("position", "bed", "blanket", "wheelchair", "clothing"), questionByLanguage = mapOf("sl" to "Kaj je neudobno?")),
        starter("clothing", "OBLAČILO", "Neudobno je oblačilo.", "care.clothing", "NEED", "care", listOf("oblačilo", "neudobno"), visibleUnderIds = listOf("uncomfortable")),
        starter("bed", "POSTELJA", "Rada bi v posteljo.", "care.bed", "NEED", "care", listOf("postelja", "nega"), visibleUnderIds = listOf("care")),
        starter("movement_pain", "BOLI PRI PREMIKU", "Boli me pri premiku.", "care.movement_pain", "PAIN", "care", listOf("premik", "boli"), visibleUnderIds = listOf("care")),

        starter("pain", "BOLI ME", "Boli me.", "pain.general", "PAIN", "pain", listOf("bolečina", "boli"), placements = pageOne(6), opensSubicons = true, children = listOf("head", "arm", "leg", "belly", "back", "chest", "throat"), questionByLanguage = mapOf("sl" to "Kje te boli?", "uk" to "Де тебе болить?", "en" to "Where does it hurt?"), imagePath = "system/pain.png", iconSource = IconSource.SYSTEM),
        starter("head", "GLAVA", "Boli me glava.", "pain.head", "PAIN", "pain", listOf("glava", "bolečina"), placements = pageFour(6)),
        starter("arm", "ROKA", "Boli me roka.", "pain.arm", "PAIN", "pain", listOf("roka", "bolečina"), placements = pageFour(7)),
        starter("leg", "NOGA", "Boli me noga.", "pain.leg", "PAIN", "pain", listOf("noga", "bolečina"), placements = pageFour(8)),
        starter("back", "HRBET", "Boli me hrbet.", "pain.back", "PAIN", "pain", listOf("hrbet", "bolečina"), placements = pageFour(9)),
        starter("belly", "TREBUH", "Boli me trebuh.", "pain.belly", "PAIN", "pain", listOf("trebuh", "bolečina"), placements = pageFour(10)),
        starter("chest", "PRSI", "Boli me v prsih.", "pain.chest", "PAIN", "pain", listOf("prsi", "bolečina"), placements = pageFour(11)),
        starter("throat", "GRLO", "Boli me grlo.", "pain.throat", "PAIN", "pain", listOf("grlo", "bolečina"), placements = pageFour(12)),
        starter("left_side", "LEVA", "Na levi strani.", "pain.left", "PAIN", "pain", listOf("leva", "stran"), placements = pageFour(13)),
        starter("right_side", "DESNA", "Na desni strani.", "pain.right", "PAIN", "pain", listOf("desna", "stran"), placements = pageFour(14)),
        starter("other_body", "DRUGO", "Boli drugje.", "pain.other", "PAIN", "pain", listOf("drugo", "bolečina"), placements = pageFour(15)),
        starter("pain_light", "MALO", "Malo boli.", "pain.light", "PAIN", "pain", listOf("malo_boli", "bolečina")),
        starter("pain_medium", "SREDNJE", "Srednje močno boli.", "pain.medium", "PAIN", "pain", listOf("srednje", "bolečina"), placements = pageFour(17)),
        starter("pain_strong", "MOČNO", "Močno boli.", "pain.strong", "PAIN", "pain", listOf("močno_boli", "bolečina"), placements = pageFour(18)),
        starter("pain_very", "ZELO", "Zelo boli.", "pain.very", "PAIN", "pain", listOf("zelo", "bolečina"), visibleUnderIds = listOf("pain")),
        starter("pain_very_strong", "ZELO MOČNO", "Zelo močno boli.", "pain.very_strong", "PAIN", "pain", listOf("zelo_močno", "bolečina"), placements = pageFour(19)),
        starter("pain_now", "ZDAJ", "Boli me zdaj.", "pain.now", "PAIN", "pain", listOf("zdaj", "bolečina"), visibleUnderIds = listOf("pain")),
        starter("pain_today", "DANES", "Boli me od danes.", "pain.today", "PAIN", "pain", listOf("danes", "bolečina"), visibleUnderIds = listOf("pain")),
        starter("pain_many_days", "VEČ DNI", "Boli me več dni.", "pain.many_days", "PAIN", "pain", listOf("več_dni", "bolečina"), visibleUnderIds = listOf("pain")),

        starter("good", "DOBRO SEM", "Dobro sem.", "feeling.good", "FEELING", "feeling", listOf("dobro", "počutje"), visibleUnderIds = listOf("feeling")),
        starter("bad", "SLABO SEM", "Slabo se počutim.", "feeling.bad", "FEELING", "feeling", listOf("slabo", "počutje"), visibleUnderIds = listOf("feeling", "problem")),
        starter("afraid", "STRAH ME JE", "Strah me je.", "feeling.afraid", "FEELING", "feeling", listOf("strah", "počutje"), visibleUnderIds = listOf("feeling", "problem")),
        starter("dont_know_problem", "NE VEM", "Ne vem.", "problem.dont_know", "QUESTION", "problem", listOf("ne_vem", "težava"), visibleUnderIds = listOf("problem")),
        starter("angry", "JEZNA SEM", "Jezna sem.", "feeling.angry", "FEELING", "feeling", listOf("jezna", "počutje"), visibleUnderIds = listOf("feeling")),
        starter("sad", "ŽALOSTNA SEM", "Žalostna sem.", "feeling.sad", "FEELING", "feeling", listOf("žalostna", "počutje"), placements = pageTwo(21), visibleUnderIds = listOf("feeling")),
        starter("happy", "VESELA SEM", "Vesela sem.", "feeling.happy", "FEELING", "feeling", listOf("vesela", "počutje"), placements = pageTwo(20), visibleUnderIds = listOf("feeling")),
        starter("cold", "MRAZ MI JE", "Mraz mi je.", "feeling.cold", "FEELING", "feeling", listOf("zebe", "mraz"), visibleUnderIds = listOf("feeling", "problem")),
        starter("hot", "VROČE MI JE", "Vroče mi je.", "feeling.hot", "FEELING", "feeling", listOf("vroče", "počutje"), visibleUnderIds = listOf("feeling", "problem")),
        starter("peace", "MIR", "Rada bi mir.", "feeling.peace", "FEELING", "feeling", listOf("mir", "počutje"), visibleUnderIds = listOf("feeling")),

        starter("dusan", "DUŠAN", "Prosim, pokličite Dušana.", "people.dusan", "PEOPLE", "people", listOf("dušan", "družina"), placements = pageTwo(11)),
        starter("daughter", "HČERKA", "Prosim, pokličite hčerko.", "people.daughter", "PEOPLE", "people", listOf("hčerka", "družina"), visibleUnderIds = listOf("call")),
        starter("son", "SIN", "Prosim, pokličite sina.", "people.son", "PEOPLE", "people", listOf("sin", "družina"), visibleUnderIds = listOf("call")),
        starter("therapist", "TERAPEVT", "Prosim, pokličite terapevta.", "people.therapist", "PEOPLE", "people", listOf("terapevt", "oseba"), visibleUnderIds = listOf("call")),
        starter("doctor", "ZDRAVNIK", "Prosim, pokličite zdravnika.", "people.doctor", "PEOPLE", "people", listOf("zdravnik", "oseba"), visibleUnderIds = listOf("call", "health", "need")),
        starter("nurse", "MEDICINSKA SESTRA", "Prosim, pokličite medicinsko sestro.", "people.nurse", "PEOPLE", "people", listOf("medicinska_sestra", "oseba"), visibleUnderIds = listOf("call", "health", "need")),
        starter("who_is_coming", "KDO PRIHAJA", "Kdo prihaja?", "people.who_is_coming", "QUESTION", "people", listOf("kdo", "prihaja")),
        starter("when_come", "KDAJ PRIDE?", "Kdaj pride?", "people.when_come", "QUESTION", "people", listOf("kdaj", "pride"), placements = pageTwo(18), visibleUnderIds = listOf("when_root")),
        starter("when_go", "KDAJ GREMO?", "Kdaj gremo?", "question.when_go", "QUESTION", "question", listOf("kdaj", "gremo"), visibleUnderIds = listOf("when_root")),
        starter("when_therapy", "KDAJ BO TERAPIJA?", "Kdaj bo terapija?", "question.when_therapy", "QUESTION", "question", listOf("kdaj", "terapija"), visibleUnderIds = listOf("when_root")),
        starter("when_home", "KDAJ DOMOV?", "Kdaj gremo domov?", "question.when_home", "QUESTION", "question", listOf("kdaj", "domov"), visibleUnderIds = listOf("when_root")),
        starter("when_eat", "KDAJ JEMO?", "Kdaj jemo?", "question.when_eat", "QUESTION", "question", listOf("kdaj", "jemo"), visibleUnderIds = listOf("when_root")),
        starter("medicine", "ZDRAVILO", "Prosim za zdravilo.", "health.medicine", "NEED", "health", listOf("zdravilo", "zdravje"), visibleUnderIds = listOf("health")),
        starter("therapy", "TERAPIJA", "Kdaj je terapija?", "health.therapy", "QUESTION", "health", listOf("terapija", "zdravje"), visibleUnderIds = listOf("health", "need")),

        starter("wheelchair", "VOZIČEK", "Prosim, pripravite voziček.", "mobility.wheelchair", "NEED", "mobility", listOf("voziček", "premik"), visibleUnderIds = listOf("care", "need")),
        starter("crutch", "BERGLA", "Prosim, pomagajte mi z berglo.", "mobility.crutch", "NEED", "mobility", listOf("bergla", "varnost"), visibleUnderIds = listOf("care", "need")),
        starter("not_safe", "NE VARNO", "Ne počutim se varno.", "mobility.not_safe", "FEELING", "mobility", listOf("varnost", "ne_varno")),
        starter("stop_movement", "USTAVIMO SE", "Ustavimo se, prosim.", "mobility.stop", "CORE_ACTION", "mobility", listOf("ustavimo", "varnost")),
        starter("need_rest", "RABIM POČITEK", "Rabim počitek.", "mobility.rest", "NEED", "mobility", listOf("počitek", "utrujena")),
        starter("fear_falling", "STRAH PASTI", "Strah me je, da bom padla.", "mobility.fear_falling", "FEELING", "mobility", listOf("padec", "strah")),
        starter("help_to_wc", "POMAGAJTE MI DO WC", "Prosim, pomagajte mi do stranišča.", "mobility.help_to_wc", "NEED", "mobility", listOf("wc", "pomoč", "varno")),
        starter("vending_drinks", "AVTOMAT PIJAČ", "Prosim, pomagajte mi pri avtomatu za pijače.", "scenario.vending_drinks", "SCENARIO", "scenario", listOf("avtomat", "pijače"), visibleUnderIds = listOf("real_world"), opensSubicons = true, children = listOf("drink_fanta", "drink_coca_cola", "drink_pepsi", "water", "juice"), questionByLanguage = mapOf("sl" to "Kaj želiš izbrati?")),
        starter("vending_coffee_tea", "AVTOMAT KAVA/ČAJ", "Prosim, pomagajte mi pri avtomatu za kavo in čaj.", "scenario.vending_coffee_tea", "SCENARIO", "scenario", listOf("avtomat", "kava", "čaj"), visibleUnderIds = listOf("real_world"), opensSubicons = true, children = listOf("coffee", "tea", "drink_milk", "vending_photo_step_1", "vending_photo_step_2"), questionByLanguage = mapOf("sl" to "Kaj želiš izbrati?")),
        starter("shop", "TRGOVINA", "Prosim, pomagajte mi v trgovini.", "scenario.shop", "SCENARIO", "scenario", listOf("trgovina", "real_world"), visibleUnderIds = listOf("real_world")),
        starter("restaurant", "RESTAVRACIJA", "Prosim, pomagajte mi v restavraciji.", "scenario.restaurant", "SCENARIO", "scenario", listOf("restavracija", "real_world"), visibleUnderIds = listOf("real_world")),
        starter("transport", "PREVOZ", "Prosim, pomagajte mi pri prevozu.", "scenario.transport", "SCENARIO", "scenario", listOf("prevoz", "real_world"), visibleUnderIds = listOf("real_world")),
        starter("vending_photo_step_1", "KORAK 1", "Poglejte sliko prvega koraka.", "scenario.vending_photo_step_1", "SCENARIO", "scenario", listOf("foto", "korak", "avtomat"), visibleUnderIds = listOf("vending_coffee_tea")),
        starter("vending_photo_step_2", "KORAK 2", "Poglejte sliko drugega koraka.", "scenario.vending_photo_step_2", "SCENARIO", "scenario", listOf("foto", "korak", "avtomat"), visibleUnderIds = listOf("vending_coffee_tea")),
        starter("move_me", "PREMAKNITE ME", "Prosim, premaknite me.", "mobility.move_me", "NEED", "mobility", listOf("premik", "pomoč"))
    )

    private fun starter(
        id: String,
        label: String,
        speech: String,
        meaningId: String,
        meaningType: String,
        meaningGroup: String,
        semanticTags: List<String>,
        visibleUnderIds: List<String> = emptyList(),
        addsToSentence: Boolean = false,
        fixedTopRowPosition: Int? = null,
        placements: List<AacPlacement> = emptyList(),
        opensSubicons: Boolean = false,
        children: List<String> = emptyList(),
        questionByLanguage: Map<String, String> = emptyMap(),
        targetPageId: String = "",
        imagePath: String = "",
        iconSource: IconSource = IconSource.SYSTEM
    ): AacItem {
        return AacItem(
            id = id,
            labelSl = label,
            imagePath = imagePath,
            actionType = when {
                targetPageId.isNotBlank() -> "open_page"
                opensSubicons -> "open_subicons"
                else -> "speak"
            },
            targetPageId = targetPageId,
            speakTextSl = speech,
            speechText = speech,
            iconSource = iconSource,
            isRootItem = visibleUnderIds.isEmpty(),
            isHiddenUntilParent = false,
            visibleUnderIds = visibleUnderIds,
            children = children,
            placements = placements,
            questionByLanguage = questionByLanguage,
            addsToSentence = addsToSentence,
            speaksImmediately = !opensSubicons,
            opensSubicons = opensSubicons,
            meaningId = meaningId,
            meaningType = meaningType,
            meaningGroup = meaningGroup,
            fixedTopRowPosition = fixedTopRowPosition,
            semanticTags = semanticTags,
            searchKeywordsByLanguage = mapOf("sl" to semanticTags),
            priority = START_PRIORITY + STARTER_IDS.indexOf(id).takeIf { it >= 0 }.orZero()
        )
    }

    private fun pageOne(position: Int): List<AacPlacement> {
        return listOf(AacPlacement(pageId = "page_1", position5x5 = position))
    }

    private fun pageTwo(position: Int): List<AacPlacement> {
        return listOf(AacPlacement(pageId = "page_2", position5x5 = position))
    }

    private fun pageThree(position: Int): List<AacPlacement> {
        return listOf(AacPlacement(pageId = "page_3", position5x5 = position))
    }

    private fun pageFour(position: Int): List<AacPlacement> {
        return listOf(AacPlacement(pageId = "page_4", position5x5 = position))
    }

    private fun Int?.orZero(): Int = this ?: 0

    private const val START_PRIORITY = 100
    private val STARTER_IDS = listOf(
        "no", "yes", "dont_understand", "thank_you", "sorry", "help", "wait", "repeat", "repeat_question", "repeat_last_sentence", "repeat_slower",
        "slower", "slower_little", "slower_much", "understand",
        "people", "need", "problem", "what_root", "where_root", "when_root", "home", "other", "real_world", "cannot", "cold_hot",
        "family_group", "friends_group", "call", "message", "miss_someone",
        "thirsty", "hungry", "pain", "wc", "tired", "what_do", "what_is_this", "what_is_happening", "what_next", "what_did_i_say",
        "where_go", "where_zana", "where_dusan", "where_are_we", "where_phone", "where_wheelchair", "miss_little", "miss_very",
        "dressing", "position", "i_want", "dont_want",
        "rest", "drink", "food", "feeling", "care", "health",
        "sister_zana", "grandfather_sergej", "julija", "oksana", "inna",
        "dusan", "franc", "miss_you", "love_you", "sorry", "please", "call_me", "when_come", "when_go", "when_therapy", "when_home", "when_eat",
        "come_to_me", "look_at_me", "turn_me", "turn_left", "turn_right", "turn_back", "turn_side", "fix_me",
        "cannot_speak", "cannot_stand", "cannot_drink", "cannot_eat", "cannot_move", "cannot_understand", "happy",
        "sad", "contact_message", "contact_call", "contact_help", "back_to_main",
        "person_dusan", "person_zana", "person_sergej", "person_julija", "person_oksana", "person_inna",
        "person_franc", "person_other", "person_where_is", "person_tell", "friend_1", "friend_2", "friend_3",
        "water", "coffee", "tea", "juice", "drink_fanta", "drink_coca_cola", "drink_pepsi", "drink_milk",
        "drink_warm", "drink_cold", "drink_small", "drink_more", "drink_no_additive", "coffee_plain", "coffee_white", "coffee_cappuccino",
        "soup", "bread", "fruit", "meat", "sweet", "other_food", "food_yogurt", "food_banana",
        "food_apple", "food_lunch", "food_dinner", "food_little", "food_more", "food_enough", "food_later",
        "head", "arm", "leg", "back", "belly", "chest", "throat", "left_side", "right_side", "other_body",
        "pain_light", "pain_medium", "pain_strong", "pain_very", "pain_very_strong", "pain_now", "pain_today", "pain_many_days",
        "water_detail", "cold_water", "warm_water", "non_sparkling_water", "sparkling_water", "not_thirsty",
        "not_hungry", "diaper", "wc_now", "wc_soon", "wc_help", "dressing_help", "washing_help", "body_position", "pillow", "blanket", "uncomfortable",
        "clothing", "bed", "movement_pain",
        "pain_area", "good", "bad", "afraid", "dont_know_problem", "angry", "cold", "hot", "peace",
        "daughter", "son", "therapist", "doctor", "nurse", "who_is_coming", "medicine", "therapy",
        "wheelchair", "crutch", "not_safe", "stop_movement", "need_rest", "fear_falling", "help_to_wc",
        "vending_drinks", "vending_coffee_tea", "shop", "restaurant", "transport", "vending_photo_step_1", "vending_photo_step_2", "move_me",
        "more"
    )
}
